---
abstract: 'HTML attribute info lookup from IRC'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-HTML-AttributeInfo
provides:
  POE::Component::IRC::Plugin::HTML::AttributeInfo:
    file: lib/POE/Component/IRC/Plugin/HTML/AttributeInfo.pm
    version: 0.004
  POE::Component::IRC::Plugin::HTML::AttributeInfo::Data:
    file: lib/POE/Component/IRC/Plugin/HTML/AttributeInfo/Data.pm
    version: 0.004
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Component::IRC::Plugin::BaseWrap: 0.004
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
